### ISSUE TITLE
Divide instruction behaves differently from IR Simulator

### ISSUE THREAD

**Issue by salty-Frankenstein** [hexclover/better_irsim#1]
Divide instruction behaves differently from IR Simulator, specifically when the dividend is negative.
```
FUNCTION main :
t$1 := #-3 / #2
WRITE t$1
RETURN #0
```
The result is `-1`, while the IR Simulator yields `-2`. Not sure if it's a bug or a feature?

**Comment by hexclover** [comment]
Fixed in commit b58b5b3956ee13af62e16d3955e2e7d9012cba66.
Please try running this program with:
- `irsim_cli div.ir`
- `irsim_cli -division trunc div.ir`
- `irsim_cli -division rounddown div.ir`

Expected output: `-2`, `-1`, `-2`.
